"""empty message

Revision ID: a78e20f31736
Revises: c6d78eacb1ce
Create Date: 2025-05-24 13:15:42.598232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78e20f31736'
down_revision: Union[str, None] = 'c6d78eacb1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departaments',
    sa.Column('departament_id', sa.Integer(), nullable=False),
    sa.Column('departament_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('departament_id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('departament_id', sa.Integer(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['departament_id'], ['departaments.departament_id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('salaries',
    sa.Column('salary_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('salary_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('salary_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salaries')
    op.drop_table('employees')
    op.drop_table('departaments')
    # ### end Alembic commands ###